<?php

/**
 * PostFinance Checkout Magento 1
 *
 * This Magento extension enables to process payments with PostFinance Checkout (https://postfinance.ch/en/business/products/e-commerce/postfinance-checkout-all-in-one.html/).
 *
 * @package PostFinanceCheckout_Payment
 * @author wallee AG (http://www.wallee.com/)
 * @license http://www.apache.org/licenses/LICENSE-2.0  Apache Software License (ASL 2.0)
 */

/* @var PostFinanceCheckout_Payment_Block_Adminhtml_Sales_Order_Invoice_View $block */
$block = $this;

/* @var PostFinanceCheckout_Payment_Helper_Data $helper */
$helper = $block->helper('postfinancecheckout_payment');
?>
<?php if ($block->isInvoicePending()) : ?>
    <div id="messages">
        <ul class="messages">
            <li class="notice-msg">
                <ul>
                    <li>
                        <span>
                            <?php echo $block->escapeHtml(
                                $helper->__('The capture has been requested but could not be completed yet. The invoice will be updated, as soon as the capture is done.')
                            ) ?>
                        </span>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
<?php endif; ?>