<?php

/**
 * PostFinance Checkout Magento 1
 *
 * This Magento extension enables to process payments with PostFinance Checkout (https://www.postfinance.ch/checkout/).
 *
 * @package PostFinanceCheckout_Payment
 * @author wallee AG (http://www.wallee.com/)
 * @license http://www.apache.org/licenses/LICENSE-2.0  Apache Software License (ASL 2.0)
 */

/* @var PostFinanceCheckout_Payment_Block_Adminhtml_Notification $block */
$block = $this;

/* @var PostFinanceCheckout_Payment_Helper_Data $helper */
$helper = $block->helper('postfinancecheckout_payment');

$numberOfManualTasks = $block->getNumberOfManualTasks();
$totalNumberOfManualTasks = array_sum($numberOfManualTasks);
?>

<?php if ($block->isAdminNotificationEnabled() && $totalNumberOfManualTasks > 0) : ?>
    <div class="notification-global notification-global-notice">
        <span class="f-right">
            <?php if (count($numberOfManualTasks) == 1) : ?>
                <a
                    href="<?php echo $block->escapeHtml($block->getManualTasksUrl(key($numberOfManualTasks))) ?>"
                    target="_blank">
                    <?php echo $block->escapeHtml($helper->__('View in PostFinance Checkout')) ?>
                </a>
            <?php else : ?>
                <a
                    href="<?php echo $block->escapeHtml($block->getManualTasksUrl()) ?>"
                    target="_blank">
                    <?php echo $block->escapeHtml($helper->__('View in PostFinance Checkout')) ?>
                </a>
            <?php endif; ?>
        </span>
        <strong><?php echo $block->escapeHtml($helper->__('PostFinance Checkout:')) ?></strong>
        <?php if ($totalNumberOfManualTasks == 1) : ?>
            <?php echo $block->escapeHtml($helper->__('There is a manual task that needs your attention.')) ?>
        <?php else : ?>
            <?php echo $block->escapeHtml(
                $helper->__(
                   'There are %s manual tasks that need your attention.',
                    $totalNumberOfManualTasks
                )
            ) ?>
        <?php endif; ?>
    </div>
<?php endif; ?>